# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092

# ??????????? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ????????? H2 ????
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

app.kafka.topic=t1_demo_metrics

# ????? ?????? ??? ??????
app.metrics.time-limit=1000

# ???????????
app.cache.time-to-live=60