# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# ????????? ????????
app.metrics.time-limit=1000
app.metrics.kafka-topic=t1_demo_metrics
app.datasource.kafka-topic=t1_demo_metrics

# ????????????
logging.level.org.springframework.kafka=INFO
logging.level.org.example.aspect=DEBUG