app:
  metrics:
    time-limit: 1000
    kafka-topic: t1_demo_metrics
  datasource:
    kafka-topic: t1_demo_metrics
  cache:
    time-to-live: 30

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: transaction-group
      auto-offset-reset: earliest

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

